Dz2
qwor/cpp_dz2_tp pull request #1
Opened 2022-10-24 14:57 UTC by qwor

2022-11-01 11:07 UTC, DPeshkoff requested changes
Привет! Посмотрел решение, есть замечания.

| Критерий | Предварительный балл | Максимальный балл | Комментарий |
|---|---|---|---|
| 1) обращение по индексам к элементам, извлечение диагонали, строки или столбца | 0.75 | 1 | Извлечение диагонали, строки, столбца не покрыты тестами |
| 2) возможность создания матрицы из векторов или чисел, вектора из чисел | 0.75 | 1 | Нужны тесты |
| 3) поэлементное сложение/вычитание/умножение объектов одинаковой размерности | 1 | 1 |  |
| 4) умножение числа на матрицу, вектора на матрицу, матрицы на вектор и матрицы на матрицу | 0.75 | 1 | Нужны тесты |
| 5) суммирование/вычитание числа и вектора/матрицы, матрицы и вектора (с возможностью выбора - по строкам/по столбцам) | 0.75 | 1 | Нужны тесты |
| 6) получение транспонированной и обратной матриц | 1 | 1 |  |
| 7) подсчёт определителя матрицы | 1 | 1 |  |
|---|---|---|---|
| Дополнительно: поддержка слайсов | 1 | 1 |  |
| Дополнительно: шаблонные параметры  | 2 | 2 | Нужно лучше покрыть тестами |
|---|---|---|---|
| Σ  | 9 | 10 |  |

Неделя на исправление замечаний: дедлайн 8 ноября

2022-11-01 12:11 UTC, qwor commented on matrices/include/Matrix.h
> +  enum VectorType {
шаблоны работают только при константных значениях параметров, поэтому добавил значения по умолчанию. Таким образом можно динамически создавать матрицы. Поэтому же все методы работают с полями rows_ и cols_, а не с шаблонными параметрами. Перечисление VectorType нужно для указания, как складывать матрицу и вектор (горизонтально или вертикально). Может можно как-то получше сделать, не знаю

2022-11-01 12:13 UTC, qwor commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Не хотелось себя ограничивать. Хотел еще 23 добавить, чтобы был доступ к operator[](arg1, arg2, arg3), но он у меня не скомпилировался почему-то. А типа нужно выбирать минимальный рабочий стандарт, или что?

2022-11-01 12:14 UTC, qwor commented on matrices/include/Matrix.h
> +  assert(cols_ == rows_);
Типа exception кидать, если матрица не квадратная?

2022-11-03 16:44 UTC, qwor commented
Исправил замечания:

- Добавил пустые строки в конец каждого файла
- Тесты собираются с санитайзерами address и undefined
- Исправил стандарт на C++ 14, так как следующие версии не используются
- Убрал assert, переделал на исключения
- Добавил pragma once
- Убрал закомментированные куски кода
- Везде, где можно, заменил инкремент {var}++ на ++{var}
- Покрыл тестами весь код, разбил арифметические тесты на разные тесты
- Заменил Print на friend ostream& operator<<
- Много других изменений по архитектуре (дефолтная операция перегрузки это теперь +=, а + вызывает +=)

2022-11-05 19:20 UTC, DPeshkoff commented on matrices/include/Matrix.h
> +  assert(cols_ == rows_);
Да, аналогично во всех остальных проверках

2022-11-18 20:32 UTC, DPeshkoff commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Достаточно просто обосновать выбор)

2022-11-18 20:58 UTC, DPeshkoff approved these changes
Привет! Провел вторую итерацию ревью.

| Критерий | Предварительный балл | Максимальный балл | Комментарий |
|---|---|---|---|
| 1) обращение по индексам к элементам, извлечение диагонали, строки или столбца | 1 | 1 |  |
| 2) возможность создания матрицы из векторов или чисел, вектора из чисел | 1 | 1 |  |
| 3) поэлементное сложение/вычитание/умножение объектов одинаковой размерности | 1 | 1 |  |
| 4) умножение числа на матрицу, вектора на матрицу, матрицы на вектор и матрицы на матрицу | 1 | 1 |  |
| 5) суммирование/вычитание числа и вектора/матрицы, матрицы и вектора (с возможностью выбора - по строкам/по столбцам) | 1 | 1 |  |
| 6) получение транспонированной и обратной матриц | 1 | 1 |  |
| 7) подсчёт определителя матрицы | 1 | 1 |  |
|---|---|---|---|
| Дополнительно: поддержка слайсов | 1 | 1 |  |
| Дополнительно: шаблонные параметры  | 2 | 2 |  |
|---|---|---|---|
| Σ  | 10 | 10 |  |

2022-11-19 07:05 UTC, merged